name = "quechua-aventuras"
compatibility_date = "2026-08-08"
main = "src/worker/index.ts"

[site]
bucket = "dist"

[[kv_namespaces]]
binding = "CONTACT_CONFIG"
id = "ea2e80fcfdeb42339380eec946960a90"
preview_id = "ea2e80fcfdeb42339380eec946960a90"

[build]
command = "npm run build"
cwd = "./"
